export const products = [
  {
    id: 1,
    title: "Avocado Chicken Bowl",
    description: "Protein-rich bowl with grilled chicken and creamy avocado.",
    price: 249,
    discount: 10,
    tag: "recipe",
    category: "lunch",
    image: "https://source.unsplash.com/150x150/?chicken,avocado",
  },
  {
    id: 2,
    title: "Organic Brown Rice",
    description: "High-fiber rice, perfect for meal prep.",
    price: 89,
    discount: 5,
    tag: "grocery",
    category: "grains",
    image: "https://source.unsplash.com/150x150/?brown-rice",
  },
  {
    id: 3,
    title: "Almond Butter Spread",
    description: "Smooth almond butter with no added sugar.",
    price: 199,
    discount: 15,
    tag: "pantry",
    category: "spreads",
    image: "https://source.unsplash.com/150x150/?almond,butter",
  },
  {
    id: 4,
    title: "Greek Yogurt Parfait",
    description: "Layered yogurt with berries and granola.",
    price: 129,
    discount: 10,
    tag: "recipe",
    category: "breakfast",
    image: "https://source.unsplash.com/150x150/?yogurt,parfait",
  },
  {
    id: 5,
    title: "Quinoa",
    description: "Superfood grain, gluten-free and rich in protein.",
    price: 159,
    discount: 5,
    tag: "grocery",
    category: "grains",
    image: "https://source.unsplash.com/150x150/?quinoa",
  },
  {
    id: 6,
    title: "Canned Chickpeas",
    description: "Ready-to-use chickpeas for hummus or salads.",
    price: 59,
    discount: 10,
    tag: "pantry",
    category: "legumes",
    image: "https://source.unsplash.com/150x150/?chickpeas",
  },
  {
    id: 7,
    title: "Fruit Smoothie Pack",
    description: "Frozen fruits blend for healthy smoothies.",
    price: 149,
    discount: 12,
    tag: "recipe",
    category: "beverage",
    image: "https://source.unsplash.com/150x150/?smoothie,fruit",
  },
  {
    id: 8,
    title: "Natural Peanut Butter",
    description: "Crunchy peanut butter, 100% peanuts.",
    price: 129,
    discount: 8,
    tag: "pantry",
    category: "spreads",
    image: "https://source.unsplash.com/150x150/?peanut,butter",
  },
  {
    id: 9,
    title: "Whole Wheat Pasta",
    description: "High-fiber pasta made from 100% whole wheat.",
    price: 119,
    discount: 7,
    tag: "grocery",
    category: "grains",
    image: "https://source.unsplash.com/150x150/?wholewheat,pasta",
  },
  {
    id: 10,
    title: "Granola Snack Mix",
    description: "Crunchy granola with nuts and dried fruits.",
    price: 89,
    discount: 5,
    tag: "pantry",
    category: "snacks",
    image: "https://source.unsplash.com/150x150/?granola,mix",
  },
  {
    id: 11,
    title: "Veggie Stir Fry Kit",
    description: "Pre-cut veggies ready to toss and cook.",
    price: 179,
    discount: 10,
    tag: "recipe",
    category: "dinner",
    image: "https://source.unsplash.com/150x150/?vegetables,stirfry",
  },
  {
    id: 12,
    title: "Olive Oil (500ml)",
    description: "Cold-pressed extra virgin olive oil.",
    price: 249,
    discount: 6,
    tag: "pantry",
    category: "cooking oil",
    image: "https://source.unsplash.com/150x150/?olive,oil",
  },
  {
    id: 13,
    title: "Lentils (Masoor Dal)",
    description: "Protein-rich red lentils.",
    price: 79,
    discount: 4,
    tag: "grocery",
    category: "legumes",
    image: "https://source.unsplash.com/150x150/?lentils,masoor",
  },
  {
    id: 14,
    title: "Chia Seeds",
    description: "Nutrient-dense seeds for smoothies and baking.",
    price: 109,
    discount: 9,
    tag: "pantry",
    category: "seeds",
    image: "https://source.unsplash.com/150x150/?chia,seeds",
  },
  {
    id: 15,
    title: "Banana Oat Pancakes",
    description: "Frozen pancakes made with banana and oats.",
    price: 99,
    discount: 10,
    tag: "recipe",
    category: "breakfast",
    image: "https://source.unsplash.com/150x150/?banana,pancake",
  },
  {
    id: 16,
    title: "Protein Bars",
    description: "High-protein energy bars, chocolate flavored.",
    price: 149,
    discount: 12,
    tag: "grocery",
    category: "snacks",
    image: "https://source.unsplash.com/150x150/?protein,bar",
  },
  {
    id: 17,
    title: "Rolled Oats",
    description: "Ideal for overnight oats or porridge.",
    price: 69,
    discount: 5,
    tag: "pantry",
    category: "grains",
    image: "https://source.unsplash.com/150x150/?oats,breakfast",
  },
  {
    id: 18,
    title: "Detox Green Juice",
    description: "Cold-pressed juice with kale, spinach & apple.",
    price: 119,
    discount: 15,
    tag: "recipe",
    category: "beverage",
    image: "https://source.unsplash.com/150x150/?green,juice",
  },
  {
    id: 19,
    title: "Instant Hummus Mix",
    description: "Just add water and blend to get hummus.",
    price: 89,
    discount: 8,
    tag: "pantry",
    category: "spreads",
    image: "https://source.unsplash.com/150x150/?hummus,mix",
  },
  {
    id: 20,
    title: "Tofu Cubes (Firm)",
    description: "Plant-based protein, perfect for stir-fries.",
    price: 139,
    discount: 6,
    tag: "grocery",
    category: "protein",
    image: "https://source.unsplash.com/150x150/?tofu,protein",
  },
];
