// data/products.js

export const products = [
  {
    id: 1,
    title: "Brown Rice",
    description: "Whole grain rice, perfect for healthy meals.",
    price: 2.99,
    discount: 10,
    tag: "pantry",
    category: "grains",
  },
  {
    id: 2,
    title: "Avocados",
    description: "Fresh avocados rich in healthy fats.",
    price: 1.99,
    discount: 0,
    tag: "grocery",
    category: "fruits",
  },
  {
    id: 3,
    title: "Grilled Chicken Salad",
    description: "High-protein recipe with grilled chicken and veggies.",
    price: 5.99,
    discount: 5,
    tag: "recipe",
    category: "meal",
  },
  {
    id: 4,
    title: "Oatmeal",
    description: "Healthy oatmeal for a quick breakfast.",
    price: 3.49,
    discount: 5,
    tag: "pantry",
    category: "cereals",
  },
  {
    id: 5,
    title: "Greek Yogurt",
    description: "Protein-rich Greek yogurt for snacks or recipes.",
    price: 1.49,
    discount: 0,
    tag: "grocery",
    category: "dairy",
  },
  {
    id: 6,
    title: "Veggie Stir Fry",
    description: "Recipe made with assorted vegetables and light sauces.",
    price: 4.99,
    discount: 10,
    tag: "recipe",
    category: "meal",
  },
  {
    id: 7,
    title: "Quinoa",
    description: "Gluten-free supergrain packed with protein.",
    price: 4.29,
    discount: 15,
    tag: "pantry",
    category: "grains",
  },
  {
    id: 8,
    title: "Apples",
    description: "Crisp and sweet apples, great for snacks or recipes.",
    price: 2.49,
    discount: 5,
    tag: "grocery",
    category: "fruits",
  },
  {
    id: 9,
    title: "Pasta Primavera",
    description: "Delicious pasta with fresh vegetables.",
    price: 6.99,
    discount: 10,
    tag: "recipe",
    category: "meal",
  },
  {
    id: 10,
    title: "Canned Beans",
    description: "Essential pantry item for salads and soups.",
    price: 1.99,
    discount: 5,
    tag: "pantry",
    category: "canned",
  },
  {
    id: 11,
    title: "Spinach",
    description: "Fresh spinach leaves for salads and smoothies.",
    price: 1.29,
    discount: 0,
    tag: "grocery",
    category: "vegetables",
  },
  {
    id: 12,
    title: "Protein Smoothie",
    description: "Recipe for a post-workout smoothie with banana and whey.",
    price: 3.99,
    discount: 5,
    tag: "recipe",
    category: "drink",
  },
  {
    id: 13,
    title: "Almond Butter",
    description: "Healthy spread made from roasted almonds.",
    price: 5.99,
    discount: 10,
    tag: "pantry",
    category: "spreads",
  },
  {
    id: 14,
    title: "Bananas",
    description: "Ripe bananas rich in potassium.",
    price: 1.10,
    discount: 0,
    tag: "grocery",
    category: "fruits",
  },
  {
    id: 15,
    title: "Avocado Toast",
    description: "Simple and nutritious breakfast recipe.",
    price: 2.99,
    discount: 10,
    tag: "recipe",
    category: "meal",
  }
];
