import { StyleSheet } from 'react-native';

const accountStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f2f4f8',
  },
  header: {
    paddingHorizontal: 24,
    paddingVertical: 18,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1e1e1e',
    textAlign: 'center',
  },
  photoSection: {
    backgroundColor: '#ffffff',
    alignItems: 'center',
    paddingVertical: 40,
    marginTop: 24,
    marginHorizontal: 20,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  photoContainer: {
    position: 'relative',
    marginBottom: 20,
  },
  profilePhoto: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 4,
    borderColor: '#e0e0e0',
  },
  editPhotoButton: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    backgroundColor: '#007bff',
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
    elevation: 3,
  },
  editPhotoText: {
    fontSize: 16,
    color: '#ffffff',
  },
  userName: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2c2c2c',
    marginBottom: 4,
  },
  userEmail: {
    fontSize: 15,
    color: '#7a7a7a',
    marginBottom: 12,
  },
  membershipBadge: {
    backgroundColor: '#28a745',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 18,
  },
  membershipText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  menuSection: {
    marginTop: 30,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#4b4b4b',
    marginBottom: 12,
    marginLeft: 5,
  },
  menuContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 5,
    elevation: 3,
    overflow: 'hidden',
  },
  menuButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  logoutButton: {
    backgroundColor: '#fff0f0',
  },
  menuButtonLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  iconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f1f3f5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  logoutIconContainer: {
    backgroundColor: '#ffd6d6',
  },
  iconText: {
    fontSize: 20,
    color: '#444',
  },
  logoutIconText: {
    fontSize: 20,
    color: '#d00000',
  },
  menuButtonText: {
    fontSize: 17,
    fontWeight: '500',
    color: '#333',
    flex: 1,
  },
  logoutText: {
    color: '#d00000',
    fontWeight: '600',
  },
  arrowText: {
    fontSize: 22,
    color: '#ccc',
    fontWeight: '300',
  },
  logoutArrowText: {
    color: '#d00000',
  },
  separator: {
    height: 1,
    backgroundColor: '#f1f3f5',
    marginLeft: 80,
  },
  logoutSection: {
    marginTop: 24,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 4,
    overflow: 'hidden',
  },
  bottomSpacing: {
    height: 40,
  },
});

export default accountStyles;
