import { StyleSheet } from 'react-native';

const accountStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafc',
  },
  header: {
    paddingHorizontal: 24,
    paddingVertical: 22,
    backgroundColor: '#ffffff',
    borderBottomWidth: 0.5,
    borderBottomColor: '#dcdcdc',
    elevation: 2,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#222',
    textAlign: 'center',
  },
  photoSection: {
    backgroundColor: '#ffffff',
    alignItems: 'center',
    paddingVertical: 35,
    marginTop: 20,
    marginHorizontal: 16,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  photoContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  profilePhoto: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: '#e6e6e6',
  },
  editPhotoButton: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    backgroundColor: '#0A84FF',
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    elevation: 2,
  },
  editPhotoText: {
    fontSize: 16,
    color: '#ffffff',
  },
  userName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1e1e1e',
    marginBottom: 3,
  },
  userEmail: {
    fontSize: 15,
    color: '#6e6e6e',
    marginBottom: 10,
  },
  membershipBadge: {
    backgroundColor: '#34C759',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  membershipText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  menuSection: {
    marginTop: 28,
    paddingHorizontal: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#3a3a3a',
    marginBottom: 10,
    marginLeft: 5,
  },
  menuContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
  },
  menuButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  logoutButton: {
    backgroundColor: '#ffecec',
  },
  menuButtonLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  iconContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#f2f4f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  logoutIconContainer: {
    backgroundColor: '#ffcaca',
  },
  iconText: {
    fontSize: 20,
    color: '#333',
  },
  logoutIconText: {
    fontSize: 20,
    color: '#e00000',
  },
  menuButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#222',
    flex: 1,
  },
  logoutText: {
    color: '#e00000',
    fontWeight: '600',
  },
  arrowText: {
    fontSize: 22,
    color: '#ccc',
    fontWeight: '300',
  },
  logoutArrowText: {
    color: '#e00000',
  },
  separator: {
    height: 1,
    backgroundColor: '#eeeeee',
    marginLeft: 72,
  },
  logoutSection: {
    marginTop: 22,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
    overflow: 'hidden',
  },
  bottomSpacing: {
    height: 40,
  },
});

export default accountStyles;
